# Starter pipeline
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzPipline-conn'
    subscriptionId: '1fa5b70e-567f-45cc-b4e8-68966ae79adc'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'AzPipeline-rg'
    location: 'Central US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/FreeheelGreg/AzPipeline/main/create_web_app/azuredeploy.json?token=GHSAT0AAAAAACBVQ2LIXVONSM2JNLNAALRCZCW263A'
    overrideParameters: '-projectName myAzPipeline'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzPipline-conn'
    subscriptionId: '1fa5b70e-567f-45cc-b4e8-68966ae79adc'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'AzPipeline-rg'
    location: 'Central US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/FreeheelGreg/AzPipeline/main/create_web_app/azuredeploy.json?token=GHSAT0AAAAAACBVQ2LJI3C3VX6CBS3RKKLAZCW2PXQ'
    overrideParameters: '-projectName myAzPipeline'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'

  displayName: 'Azure pipeline tutorial'
